### ISSUE TITLE
Online demo?

### ISSUE THREAD

**Issue by winkler1** [jmfurlott/react-styleguide#1]
Hi-
 I'd like to add this to react.rocks. Can get to example via http://cdn.rawgit.com/jmfurlott/react-styleguide/master/demo/index.html#Footer, but main.css 404's and it probably doesn't look its best. Could you fix the path for rawgit, or put up a github.io page please?
Thanks,
Jeff

**Comment by jmfurlott** [comment]
Jeff,

Thank you very much for reaching out to me first! The demo wasn't made to
be viewed via the raw index.html on Github.  I will set up the page for you
tonight, and let you know when its done!

Thanks
Joe

On Tue, Feb 3, 2015 at 8:08 AM, Jeff Winkler notifications@github.com
wrote:

> Hi-
> I'd like to add this to react.rocks. Can get to example via
> http://cdn.rawgit.com/jmfurlott/react-styleguide/master/demo/index.html#Footer,
> but main.css 404's and it probably doesn't look its best. Could you fix the
> path for rawgit, or put up a github.io page please?
> Thanks,
> Jeff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmfurlott/react-styleguide/issues/1.

## 

Joseph Furlott

727-560-6201
jmfurlott.com
@jmfurlott http://twitter.com/jmfurlott

**Comment by jmfurlott** [comment]
Jeff,

I created a github.io page for the demo.  You can visit it at http://jmfurlott.github.io/react-styleguide .

Please let me know if you any questions, but I am gonna mark this as closed now. Thanks!

**Comment by winkler1** [comment]
Looks much better with the correct CSS, thanks! One nitpick - looks like the Footer has the button content (though it's below the fold, hard to notice :)

re: Duplicating code, this is a way to have one copy of the file. http://binarymuse.github.io/react-primer/build/ .  https://github.com/BinaryMuse/react-primer/blob/gh-pages/index.jsx -- uses Webpack to load it in both as text(webpack raw loader) and JS.

```
switch (demo) {
  case 1:
    require.ensure([], () => {
      require("./demo1/demo1.jsx");
      showDemoLink(demo, [{ name: "demo1.jsx", code: require("!!raw!./demo1/demo1.jsx")}]);
    });
```
